### ISSUE TITLE
채팅 Refactor

### ISSUE THREAD

**Issue by yuuzinn** [yuuzinn/NewChat#65]
- [ ] Kafka 채팅 Refactor

**Comment by yeb0** [comment]
TODO : Topic 1개 VS Topic 여러 개(많게는 5만개 이상) Latency 확인해보기

**Comment by yeb0** [comment]
확인해 보았으나, Topic 여러 개 해도 Latency는 상관이 없음. 12만개 정도 찍혀야 차이가 날 정도... 나중에 upgrade할 때 수정해야할 것을 보임.
